### PR TITLE
potential fix

### PR DESCRIPTION
**Pull request by arnimarj**
The comment line was the one causing the failure, but I haven't been able to verify that this does indeed fix the issue.

### CODE REVIEW

**Comment by aodj** [comment]
What is this a fix for? I don't see a linked issue.

**Comment by arnimarj** [comment]
For this one here: https://github.com/dohop/supervisor-logstash-notifier/issues/8

**Comment by aodj** [comment]
Ah ok, thats good to have. I need to look into why Travis isn't running properly and get the tests to pass, and then I'll merge 👍

**Comment by arnimarj** [comment]
I looked at the parsing code that was causing the issue, and it cut of the line after the first "#",and then tried to parse the requirement entry.

When there is only a single comment in a line, the remaining string is all whitespace, which then causes the exception.

**Pull request merged**
